// Do not edit this file; automatically generated by build.py.
"use strict";

"use strict";
Blockly.wedoLive = new Blockly.Generator("wedoLive");
Blockly.wedoLive.addReservedWords(
  "False,None,True,and,as,assert,break,class,continue,def,del,elif,else,except,exec,finally,for,from,global,if,import,in,is,lambda,nonlocal,not,or,pass,print,raise,return,try,while,with,yield,NotImplemented,Ellipsis,__debug__,quit,exit,copyright,license,credits,ArithmeticError,AssertionError,AttributeError,BaseException,BlockingIOError,BrokenPipeError,BufferError,BytesWarning,ChildProcessError,ConnectionAbortedError,ConnectionError,ConnectionRefusedError,ConnectionResetError,DeprecationWarning,EOFError,Ellipsis,EnvironmentError,Exception,FileExistsError,FileNotFoundError,FloatingPointError,FutureWarning,GeneratorExit,IOError,ImportError,ImportWarning,IndentationError,IndexError,InterruptedError,IsADirectoryError,KeyError,KeyboardInterrupt,LookupError,MemoryError,ModuleNotFoundError,NameError,NotADirectoryError,NotImplemented,NotImplementedError,OSError,OverflowError,PendingDeprecationWarning,PermissionError,ProcessLookupError,RecursionError,ReferenceError,ResourceWarning,RuntimeError,RuntimeWarning,StandardError,StopAsyncIteration,StopIteration,SyntaxError,SyntaxWarning,SystemError,SystemExit,TabError,TimeoutError,TypeError,UnboundLocalError,UnicodeDecodeError,UnicodeEncodeError,UnicodeError,UnicodeTranslateError,UnicodeWarning,UserWarning,ValueError,Warning,ZeroDivisionError,_,__build_class__,__debug__,__doc__,__import__,__loader__,__name__,__package__,__spec__,abs,all,any,apply,ascii,basestring,bin,bool,buffer,bytearray,bytes,callable,chr,classmethod,cmp,coerce,compile,complex,copyright,credits,delattr,dict,dir,divmod,enumerate,eval,exec,execfile,exit,file,filter,float,format,frozenset,getattr,globals,hasattr,hash,help,hex,id,input,int,intern,isinstance,issubclass,iter,len,license,list,locals,long,map,max,memoryview,min,next,object,oct,open,ord,pow,print,property,quit,range,raw_input,reduce,reload,repr,reversed,round,set,setattr,slice,sorted,staticmethod,str,sum,super,tuple,type,unichr,unicode,vars,xrange,zip"
);
Blockly.wedoLive.ORDER_ATOMIC = 0;
Blockly.wedoLive.ORDER_COLLECTION = 1;
Blockly.wedoLive.ORDER_STRING_CONVERSION = 1;
Blockly.wedoLive.ORDER_MEMBER = 2.1;
Blockly.wedoLive.ORDER_FUNCTION_CALL = 2.2;
Blockly.wedoLive.ORDER_EXPONENTIATION = 3;
Blockly.wedoLive.ORDER_UNARY_SIGN = 4;
Blockly.wedoLive.ORDER_BITWISE_NOT = 4;
Blockly.wedoLive.ORDER_MULTIPLICATIVE = 5;
Blockly.wedoLive.ORDER_ADDITIVE = 6;
Blockly.wedoLive.ORDER_BITWISE_SHIFT = 7;
Blockly.wedoLive.ORDER_BITWISE_AND = 8;
Blockly.wedoLive.ORDER_BITWISE_XOR = 9;
Blockly.wedoLive.ORDER_BITWISE_OR = 10;
Blockly.wedoLive.ORDER_RELATIONAL = 11;
Blockly.wedoLive.ORDER_LOGICAL_NOT = 12;
Blockly.wedoLive.ORDER_LOGICAL_AND = 13;
Blockly.wedoLive.ORDER_LOGICAL_OR = 14;
Blockly.wedoLive.ORDER_CONDITIONAL = 15;
Blockly.wedoLive.ORDER_LAMBDA = 16;
Blockly.wedoLive.ORDER_NONE = 99;
Blockly.wedoLive.ORDER_OVERRIDES = [
  [Blockly.wedoLive.ORDER_FUNCTION_CALL, Blockly.wedoLive.ORDER_MEMBER],
  [Blockly.wedoLive.ORDER_FUNCTION_CALL, Blockly.wedoLive.ORDER_FUNCTION_CALL],
  [Blockly.wedoLive.ORDER_MEMBER, Blockly.wedoLive.ORDER_MEMBER],
  [Blockly.wedoLive.ORDER_MEMBER, Blockly.wedoLive.ORDER_FUNCTION_CALL],
  [Blockly.wedoLive.ORDER_LOGICAL_NOT, Blockly.wedoLive.ORDER_LOGICAL_NOT],
  [Blockly.wedoLive.ORDER_LOGICAL_AND, Blockly.wedoLive.ORDER_LOGICAL_AND],
  [Blockly.wedoLive.ORDER_LOGICAL_OR, Blockly.wedoLive.ORDER_LOGICAL_OR],
];

Blockly.wedoLive.init = function (a) {
  Blockly.wedoLive.PASS = this.INDENT + "pass\n";
  Blockly.wedoLive.definitions_ = Object.create(null);
  Blockly.wedoLive.functionNames_ = Object.create(null);
  Blockly.wedoLive.variableDB_
    ? Blockly.wedoLive.variableDB_.reset()
    : (Blockly.wedoLive.variableDB_ = new Blockly.Names(
        Blockly.wedoLive.RESERVED_WORDS_
      ));
  Blockly.wedoLive.definitions_.variables = "";
  Blockly.wedoLive.definitions_.MotorDistUnits = "seconds";
  Blockly.wedoLive.definitions_.currentIndent = "";
  Blockly.wedoLive.definitions_.currentSpeed = "7";
  Blockly.wedoLive.definitions_.driving = !1;
  Blockly.wedoLive.definitions_.lineTrackOn = !1;
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  Blockly.wedoLive.definitions_.MusicUsed = !1;
  Blockly.wedoLive.definitions_.musicStackFlag = !1;
  Blockly.wedoLive.definitions_.musicStackString = "";
  Blockly.wedoLive.definitions_.loopVar = 0;
  Blockly.wedoLive.definitions_.inObsLoop = !1;
  Blockly.wedoLive.definitions_.clapUsed = !1;
  Blockly.wedoLive.definitions_.clapUsedEvent = !1;
  Blockly.wedoLive.definitions_.eventUsed = !1;
  Blockly.wedoLive.definitions_.inEvent = !1;
  Blockly.wedoLive.definitions_.driveInEvent = !1;
  Blockly.wedoLive.definitions_.speedChangeInEvent = !1;
  Blockly.wedoLive.definitions_.inLineSpeedtoUse = "5";
  Blockly.wedoLive.definitions_.lastUsedDriveUnits = "";
  Blockly.wedoLive.definitions_.Header =
    "";
  a = a.getTopBlocks();
  for (var b = 0, d; (d = a[b]); b++)
    d.type.includes("new_event_clap_") &&
      (Blockly.wedoLive.definitions_.clapUsedEvent = !0);
};

Blockly.wedoLive.finish = function (a) {
  Blockly.wedoLive.definitions_.clapUsed &&
    (a = a.replace(
      "#start blocks \n",
      "#start blocks \nEd.TimeWait(200, Ed.TIME_MILLISECONDS)\nEd.ReadClapSensor()\n"
    ));
  Blockly.wedoLive.definitions_.MusicUsed &&
    (Blockly.wedoLive.definitions_.Header =
      Blockly.wedoLive.definitions_.Header.replace(
        "#Ed.Tempo place hold",
        "Ed.Tempo = Ed.TEMPO_MEDIUM"
      ));
  // Blockly.wedoLive.definitions_.Header += "#---------KUKI gerated code-------------\n";
  a = Blockly.wedoLive.definitions_.Header + a;
  delete Blockly.wedoLive.definitions_;
  delete Blockly.wedoLive.functionNames_;
  Blockly.wedoLive.variableDB_.reset();
  return a;
};
Blockly.wedoLive.scrubNakedValue = function (a) {
  return a + "\n";
};
Blockly.wedoLive.quote_ = function (a) {
  a = a.replace(/\\/g, "\\\\").replace(/\n/g, "\\\n").replace(/%/g, "\\%");
  var b = "'";
  -1 !== a.indexOf("'") &&
    (-1 === a.indexOf('"') ? (b = '"') : (a = a.replace(/'/g, "\\'")));
  return b + a + b;
};
Blockly.wedoLive.scrub_ = function (a, b) {
  var d = "";
  if (!a.outputConnection || !a.outputConnection.targetConnection) {
    var c = a.getCommentText();
    (c = Blockly.utils.wrap(c, Blockly.wedoLive.COMMENT_WRAP - 3)) &&
      (d = a.getProcedureDef
        ? d + ('"""' + c + '\n"""\n')
        : d + Blockly.wedoLive.prefixLines(c + "\n", "# "));
    for (var e = 0; e < a.inputList.length; e++)
      a.inputList[e].type == Blockly.INPUT_VALUE &&
        (c = a.inputList[e].connection.targetBlock()) &&
        (c = Blockly.wedoLive.allNestedComments(c)) &&
        (d += Blockly.wedoLive.prefixLines(c, "# "));
  }
  a = a.nextConnection && a.nextConnection.targetBlock();
  a = Blockly.wedoLive.blockToCode(a);
  return d + b + a;
};
Blockly.wedoLive.getAdjustedInt = function (a, b, d, c) {
  d = d || 0;
  a.workspace.options.oneBasedIndex && d--;
  var e = a.workspace.options.oneBasedIndex ? "1" : "0";
  a =
    Blockly.wedoLive.valueToCode(
      a,
      b,
      d ? Blockly.wedoLive.ORDER_ADDITIVE : Blockly.wedoLive.ORDER_NONE
    ) || e;
  Blockly.isNumber(a)
    ? ((a = parseInt(a, 10) + d), c && (a = -a))
    : ((a =
        0 < d
          ? "int(" + a + " + " + d + ")"
          : 0 > d
          ? "int(" + a + " - " + -d + ")"
          : "int(" + a + ")"),
      c && (a = "-" + a));
  return a;
};

//! Hadi Changes in Blocks Codes


//* START EVENTS
//! ******************************************************************* */
Blockly.wedoLive.Events = {};
Blockly.wedoLive.new_event_start = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  Blockly.wedoLive.definitions_.inEvent = !1;
  Blockly.wedoLive.definitions_.lastUsedDriveUnits = "";
  return ("");
};
Blockly.wedoLive.control_stop = function (a) {
  return ("FF 55 DD 00 00 00 00-");
};
Blockly.wedoLive.event_wait_time = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 65534){
    value = 65534;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 01 00 " + result.low + " " + result.high + " 00-");
};
Blockly.wedoLive.event_button_pressed = function (a) {
  return ("FF 55 01 01 00 00 00-");
};
Blockly.wedoLive.event_message_blue = function (a) {
  return ("");
};
Blockly.wedoLive.event_message_green = function (a) {
  return ("");
};
Blockly.wedoLive.event_message_red = function (a) {
  return ("");
};
Blockly.wedoLive.event_message_pink = function (a) {
  return ("");
};
Blockly.wedoLive.event_message_purple = function (a) {
  return ("");
};
Blockly.wedoLive.event_message_orange = function (a) {
  return ("");
};

Blockly.wedoLive.control_send_message = function (a) {
    let value = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
    if(value == "1"){
      return "XBB";
    }else if(value == "2"){
      return "XRR";
    }else if(value == "3"){
      return "XGG";
    }else if(value == "4"){
      return "XPP";
    }else if(value == "5"){
      return "XVV";
    }else if(value == "6"){
      return "XOO";
    }else{
      return "";
    }

};

//* END EVENTS
//! ******************************************************************* */
//* START AI
Blockly.wedoLive.AI = {};
Blockly.wedoLive.ai_camera = function (a) {
  // var sound_animal = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  // var result = toTwoByteHex(parseInt(sound_animal));
  // return ("runJSSound("+sound_animal+");");
  return `startCameraBlock();`;
};
Blockly.wedoLive.dropdown_ai_camera_hand_detection = function (block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE];
};
Blockly.wedoLive.ai_camera_hand_detection = function (block) {
  var hand_detection = Blockly.wedoLive.valueToCode(block, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  const code = `showHideHandDetection("${hand_detection}");`;
  return code;
};
Blockly.wedoLive.dropdown_ai_gesture_detction = function (block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE];
};
Blockly.wedoLive.ai_gesture_detction = function (block) {
  Blockly.wedoLive.definitions_.loopVar += 1;
  var loopCount = Blockly.wedoLive.definitions_.loopVar;
  var gesture_choice = Blockly.wedoLive.valueToCode(block, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  var statements = Blockly.wedoLive.statementToCode(block, 'SUBSTACK');
  statements = Blockly.wedoLive.addLoopTrap(statements, block);
  var gestureCode = `
function gestureLoop_${loopCount}() {
if (!isProgramRunning()) return;
if (getGesture('${gesture_choice}')) {
${statements}
}
mySetTimeout(gestureLoop_${loopCount}, 200);
}
gestureLoop_${loopCount}();
`;
return gestureCode;
};

//* END AI
//! ******************************************************************* */
//* START SOUNDS
Blockly.wedoLive.Sounds = {};

Blockly.wedoLive.kuki_sound_on = function (a) {
  return ("waitUntilDistance(20);");
};
Blockly.wedoLive.kuki_sound_animals = function (a) {
  var sound_animal = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  var result = toTwoByteHex(parseInt(sound_animal));
  return ("runJSSound("+sound_animal+");");
};
Blockly.wedoLive.dropdown_kuki_sound_animals = function (block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE];
};
Blockly.wedoLive.kuki_sound_music = function (a) {
  var sound_music = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  var result = toTwoByteHex(parseInt(sound_music));
  return ("FF 55 05 " + result.low + " 00 00 00-");
};
Blockly.wedoLive.dropdown_kuki_sound_music = function (block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE];
};
//* END SOUNDS
//! ******************************************************************* */

//* START ONBOARD LED
Blockly.wedoLive.kuki_light = function (a) {
  var light = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  var result = toTwoByteHex(parseInt(light));
  return ("FF 55 02 " + result.low + " 00 00 00-");
};

Blockly.wedoLive.dropdown_kuki_light = function(block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE]; 
};
//* END LED LIGHT
//! ******************************************************************* */

//* START RGB LED
Blockly.wedoLive.colour_picker = function(block) {
  var code = Blockly.wedoLive.quote_(block.getFieldValue('COLOUR'));
  return [code, Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.kuki_RGB_light_OFF = function (a) {
  return ("FF 55 06 00 00 00 00-");
};

Blockly.wedoLive.kuki_RGB_light_random = function (a) {
  return "FF 55 06 02 00 00 00-";
};

Blockly.wedoLive.kuki_RGB_light = function (a) {
  var colourValue = Blockly.wedoLive.valueToCode(a, 'VALUE', Blockly.wedoLive.ORDER_NONE);
  // colourValue = colourValue.replace("#", "").replace("'#'", "").replace("'", "").replace("\"", "");
  colourValue = colourValue.replace(/['#"]/g, '');
  colourValue = HexColorToRGB(colourValue);
  return 'FF 55 06 01 ' + colourValue + "-";
};

Blockly.wedoLive.dropdown_kuki_RGB_light_color = function(block) {
  var value = block.getFieldValue('CHOICE');
  return value; 
};

Blockly.wedoLive.kuki_RGB_light_color = function (a) {
  let value = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
    if(value == "G"){
      value = "00 FF 00";
    }else if(value == "R"){
      value = "FF 00 00";
    }else if(value == "B"){
      value = "00 00 FF";
    }else if(value == "O"){
      value = "FF E3 60";
    }else if(value == "P"){
      value = "E7 00 A7";
    }else if(value == "C"){
      value = "77 E8 FF";
    }else{
      value = randomColour().replace(/['#"]/g, '');
      value = HexColorToRGB(value);
    }
  return "FF 55 06 01 " + value + "-";
};

//* END RGB LED
//! ******************************************************************* */

//* START MATRIX
Blockly.wedoLive.matrix_picker = function(block) {
  var code = this.getFieldValue('MATRIX');
  return [code, Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.kuki_matrix_btimap = function (a) {
  var displayValue =  Blockly.wedoLive.valueToCode(a, 'MATRIX', Blockly.wedoLive.ORDER_NONE);
  displayValue = matrix_Binary_to_four_segments(displayValue);
  return (displayValue+"-");
};

Blockly.wedoLive.input_text = function() {
  var code = this.getFieldValue('TEXT');
  return [code, Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.kuki_matrix_string = function (a) {
  var displayValue =  Blockly.wedoLive.valueToCode(a, 'TEXT', Blockly.wedoLive.ORDER_NONE);
  displayValue = stringToFormattedHexChunks(displayValue);
  return (displayValue+"-");
};
//* END MATRIX
//! ******************************************************************* */

//* START MOTOR STTEPPER
Blockly.wedoLive.motion = {};
Blockly.wedoLive.dropdown_kuki_speed = function (block) {
  var value = block.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE]; 
};

Blockly.wedoLive.kuki_drive_speed = function (a) {
  var speed = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_NONE);
  var result = toTwoByteHex(parseInt(speed));
  return ("FF 55 08 00 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_drive_forward = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "STEPS", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 65534){
    value = 65534;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 01 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_drive_backward = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "STEPS", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 65534){
    value = 65534;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 02 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_turn_right = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 03 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_turn_left = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 04 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_left_wheel_turn_left = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 05 " + result.low + " " + result.high + " 00-");
};
Blockly.wedoLive.kuki_left_wheel_turn_right = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 06 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_right_wheel_turn_left = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 07 " + result.low + " " + result.high + " 00-");
};

Blockly.wedoLive.kuki_right_wheel_turn_right = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "ANGLE", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 360){
    value = 360;
  }
  var result = toTwoByteHex(parseInt(value));
  return ("FF 55 08 08 " + result.low + " " + result.high + " 00-");
};

//* END MOTOR STTEPPER
//! ******************************************************************* */

//* START PEN
Blockly.wedoLive.pen = {};

Blockly.wedoLive.kuki_pen = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, 'CHOICE', Blockly.wedoLive.ORDER_NONE);

  if(value == "0"){
    //! PEN DOWN
    value = "00";
  }else if(value == "1"){
    //! PEN UP
    value = "01";
  }else if(value == "2"){
    //! PEN UP
    value = "02";
  }
  return ("FF 55 07 " + value + " 00 00 00-");
};

Blockly.wedoLive.dropdown_kuki_pen = function (a) {
  var value = a.getFieldValue('CHOICE');
  return [value, Blockly.wedoLive.ORDER_NONE]; 
};

//* END PEN
//! ******************************************************************* */

//* START CONTROL LOOP STOP
Blockly.wedoLive.loop = {};

Blockly.wedoLive.control_forever = function (a) {
  Blockly.wedoLive.definitions_.loopVar += 1;
  var loopCount = Blockly.wedoLive.definitions_.loopVar;
  loopCount = toTwoByteHex(parseInt(loopCount));

  var branch = Blockly.wedoLive.statementToCode(a, 'SUBSTACK');
  branch = Blockly.wedoLive.addLoopTrap(branch, a);
  var end_loop = "FF 55 01 05 " + loopCount.low + " 00 00-";
  var loop = "FF 55 01 03 " + loopCount.low + " 00 00-"
  return (loop + branch + end_loop);
};

Blockly.wedoLive.control_loop_number = function (a) {
  var value = Blockly.wedoLive.valueToCode(a, "TIMES", Blockly.wedoLive.ORDER_ATOMIC);
  if(value > 65534){
    value = 65534;
  }
  Blockly.wedoLive.definitions_.loopVar += 1;
  var loopCount = Blockly.wedoLive.definitions_.loopVar;
  loopCount = toTwoByteHex(parseInt(loopCount));

  var result = toTwoByteHex(parseInt(value));
  var branch = Blockly.wedoLive.statementToCode(a, 'SUBSTACK');
  branch = Blockly.wedoLive.addLoopTrap(branch, a);
  var end_loop = "FF 55 01 05 " + loopCount.low + " 00 00-";
  var loop = "FF 55 01 02 " + loopCount.low + " " + result.low + " " + result.high + "-"
  return (loop + branch + end_loop);
};

//* END CONTROL LOOP STOP
//! ******************************************************************* */

//! End Hadi Changes in Block Codes

Blockly.wedoLive.drive_backwards_time = function (a) {
  checkForDriveSpeedVar();
  var value = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  //value = value.toString(16).padStart(2, '0').toUpperCase();
  // Example usage:
  let result = toTwoByteHex(parseInt(value));
  console.log(`High Byte: 0x${result.high}, Low Byte: 0x${result.low}`);
  return ("FF 55 01 02 03 05 04 " + result.high + " " + result.low +"\n");
};

Blockly.wedoLive.dropdown_control_setloop_event = function (a) {
  a = a.getFieldValue("CHOICE");
  return [
    "circle" == a
      ? "Ed.ReadKeypad() != Ed.KEYPAD_ROUND"
      : "Ed.ReadKeypad() != Ed.KEYPAD_TRIANGLE",
    Blockly.wedoLive.ORDER_ATOMIC,
  ];
};

Blockly.wedoLive.control_loop_event = function (a) {
  var b = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  a = Blockly.wedoLive.statementToCode(a, "SUBSTACK");
  "" == a && (a = "\tpass\n");
  return "#loop until button \nwhile " + b + ":\n" + a;
};

Blockly.wedoLive.control_loop_event_obstacle = function (a) {
  var b = Blockly.wedoLive.definitions_.inObsLoop;
  Blockly.wedoLive.definitions_.inObsLoop = !0;
  a = Blockly.wedoLive.statementToCode(a, "SUBSTACK");
  Blockly.wedoLive.definitions_.inObsLoop = b;
  "" == a && (a = "\tpass\n");
  b = "";
  0 == Blockly.wedoLive.definitions_.inObsLoop &&
    (b = "Ed.ObstacleDetectionBeam(Ed.OFF)\n");
  return (
    "#loop until obs \nEd.ObstacleDetectionBeam(Ed.ON)\nwhile Ed.ReadObstacleDetection() <= Ed.OBSTACLE_NONE:\n" +
    a +
    b
  );
};





Blockly.wedoLive.dropdown_control_setwait_event = function (a) {
  a = a.getFieldValue("CHOICE");
  console.log(a);
  switch (a) {
    case "clap":
      Blockly.wedoLive.definitions_.clapUsed = !0;
      a = "Ed.ReadClapSensor()!=Ed.CLAP_DETECTED";
      break;
    case "circle":
      a = "Ed.ReadKeypad()!=Ed.KEYPAD_ROUND";
      break;
    case "triangle":
      a = "Ed.ReadKeypad()!=Ed.KEYPAD_TRIANGLE";
      break;
    case "clapTwo":
      Blockly.wedoLive.definitions_.clapUsed = !0;
      break;
    case "black":
      a = "Ed.ReadLineState()!=Ed.LINE_ON_BLACK";
      Blockly.wedoLive.definitions_.lineTrackOn ||
        ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
        (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
      break;
    case "white":
      a = "Ed.ReadLineState()!=Ed.LINE_ON_WHITE";
      0 == Blockly.wedoLive.definitions_.lineTrackOn &&
        ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
        (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
      break;
    case "left":
      a = "Ed.ReadLeftLightLevel()<=Ed.ReadRightLightLevel()";
      break;
    case "right":
      a = "Ed.ReadLeftLightLevel()>=Ed.ReadRightLightLevel()";
  }
  return [a, Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.control_wait_event = function (a) {
  var b = "#wait until event \n",
    d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  ("clapTwo" != d && "Ed.ReadClapSensor()!=Ed.CLAP_DETECTED" != d) ||
    !a.getPreviousBlock().type.includes("drive") ||
    (console.log("Drive before clap"),
    (b += "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadClapSensor()\n"));
  return "clapTwo" == d
    ? b +
        "noClaps=True\nEd.ReadClapSensor()\nwhile noClaps:\n\twhile Ed.ReadClapSensor()!=Ed.CLAP_DETECTED:\n\t\tpass\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadClapSensor()\n\tEd.TimeWait(350, Ed.TIME_MILLISECONDS)\n\tif Ed.ReadClapSensor()==Ed.CLAP_DETECTED:\n\t\tnoClaps=False\n"
    : b + "Ed.TimeWait(200, Ed.TIME_MILLISECONDS)\nwhile " + d + ":\n\tpass\n";
};

Blockly.wedoLive.control_wait_event_obstacle = function (a) {
  a = "";
  0 == Blockly.wedoLive.definitions_.inObsLoop &&
    (a = "Ed.ObstacleDetectionBeam(Ed.OFF)\n");
  return (
    "#wait until obstacle \nEd.ObstacleDetectionBeam(Ed.ON)\nwhile Ed.ReadObstacleDetection() != Ed.OBSTACLE_AHEAD:\n\tpass\n" +
    a
  );
};

Blockly.wedoLive.dropdown_control_setwait_message = function (a) {
  return [a.getFieldValue("CHOICE"), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.control_wait_message = function (a) {
  return (
    "#wait until message \nwhile Ed.ReadIRData()!=" +
    Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC) +
    ":\n\tpass\n"
  );
};
Blockly.wedoLive.dropdown_control_set_message = function (a) {
  return [a.getFieldValue("CHOICE"), Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.Drive = {};
function driveDropDownToBool(a) {
  switch (a) {
    case "left":
      a = "Ed.ReadLeftLightLevel()>Ed.ReadRightLightLevel()";
      break;
    case "right":
      a = "Ed.ReadLeftLightLevel()<Ed.ReadRightLightLevel()";
      break;
    case "white":
      a = "Ed.ReadLineState()==Ed.LINE_ON_WHITE";
      0 == Blockly.wedoLive.definitions_.lineTrackOn &&
        ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
        (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
      break;
    case "black":
      (a = "Ed.ReadLineState()==Ed.LINE_ON_BLACK"),
        Blockly.wedoLive.definitions_.lineTrackOn ||
          ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
          (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  }
  return a;
}

function checkForDriveSpeedVar() {
  0 == Blockly.wedoLive.definitions_.driving &&
    Blockly.wedoLive.definitions_.speedChangeInEvent &&
    ((Blockly.wedoLive.definitions_.Header += "DS = 5\n"),
    (Blockly.wedoLive.definitions_.driving = !0));
}

function drivePreambleChecks() {
  var a = !1;
  Blockly.wedoLive.definitions_.eventUsed &&
    (Blockly.wedoLive.definitions_.inEvent
      ? (a = Blockly.wedoLive.definitions_.driveInEvent = !0)
      : Blockly.wedoLive.definitions_.driveInEvent && (a = !0));
  return a;
}

Blockly.wedoLive.drive_forwards_time = function (a) {
  checkForDriveSpeedVar();
  var b = "#drive forwards for time\n",
    d = "",
    c = Blockly.wedoLive.definitions_.inLineSpeedtoUse;
  a = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  a *= 1e3;
  "Ed.TIME" != Blockly.wedoLive.definitions_.lastUsedDriveUnits &&
    ((Blockly.wedoLive.definitions_.lastUsedDriveUnits = "Ed.TIME"),
    (d = "Ed.DistanceUnits = Ed.TIME\n"));
  drivePreambleChecks() && (d = "Ed.DistanceUnits = Ed.TIME\n");
  Blockly.wedoLive.definitions_.speedChangeInEvent && (c = "DS");
  return (b =
    b +
    d +
    Blockly.wedoLive.definitions_.currentIndent +
    "Ed.Drive(Ed.FORWARD, " +
    c +
    ", " +
    a +
    ")\n");
};
// Blockly.wedoLive.drive_backwards_time = function (a) {
//   checkForDriveSpeedVar();
//   var b = "#drive Backwards for time\n",
//     d = "",
//     c = Blockly.wedoLive.definitions_.inLineSpeedtoUse;
//   a = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
//   a *= 1e3;
//   "Ed.TIME" != Blockly.wedoLive.definitions_.lastUsedDriveUnits &&
//     ((Blockly.wedoLive.definitions_.lastUsedDriveUnits = "Ed.TIME"),
//     (d = "Ed.DistanceUnits = Ed.TIME\n"));
//   drivePreambleChecks() && (d = "Ed.DistanceUnits = Ed.TIME\n");
//   Blockly.wedoLive.definitions_.speedChangeInEvent && (c = "DS");
//   return (b =
//     b +
//     d +
//     Blockly.wedoLive.definitions_.currentIndent +
//     "Ed.Drive(Ed.BACKWARD, " +
//     c +
//     ", " +
//     a +
//     ")\n");
// };



// Blockly.wedoLive.drive_left_angle = function (a) {
//   checkForDriveSpeedVar();
//   var b = "#drive left for angle\n",
//     d = "",
//     c = Blockly.wedoLive.definitions_.inLineSpeedtoUse;
//   a = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
//   "Ed.CM" != Blockly.wedoLive.definitions_.lastUsedDriveUnits &&
//     ((Blockly.wedoLive.definitions_.lastUsedDriveUnits = "Ed.CM"),
//     (d = "Ed.DistanceUnits = Ed.CM\n"));
//   drivePreambleChecks() && (d = "Ed.DistanceUnits = Ed.CM\n");
//   Blockly.wedoLive.definitions_.speedChangeInEvent && (c = "DS");
//   return (b =
//     b +
//     d +
//     Blockly.wedoLive.definitions_.currentIndent +
//     "Ed.Drive(Ed.FORWARD_LEFT, " +
//     c +
//     ", " +
//     a +
//     ")\n");
// };

Blockly.wedoLive.drive_left_angle = function (a) {
  let value = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  let result = toTwoByteHex(parseInt(value));
  console.log(`High Byte: 0x${result.high}, Low Byte: 0x${result.low}`);
  return ("FF 55 01 02 03 05 04 " + result.high + " " + result.low +"\n");
};

Blockly.wedoLive.drive_right_angle = function (a) {
  checkForDriveSpeedVar();
  var b = "#drive right for angle\n",
    d = "",
    c = Blockly.wedoLive.definitions_.inLineSpeedtoUse;
  a = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  "Ed.CM" != Blockly.wedoLive.definitions_.lastUsedDriveUnits &&
    ((Blockly.wedoLive.definitions_.lastUsedDriveUnits = "Ed.CM"),
    (d = "Ed.DistanceUnits = Ed.CM\n"));
  drivePreambleChecks() && (d = "Ed.DistanceUnits = Ed.CM\n");
  Blockly.wedoLive.definitions_.speedChangeInEvent && (c = "DS");
  return (b =
    b +
    d +
    Blockly.wedoLive.definitions_.currentIndent +
    "Ed.Drive(Ed.FORWARD_RIGHT, " +
    c +
    ", " +
    a +
    ")\n");
};

Blockly.wedoLive.drive_line_tracking_time = function (a) {
  a = Blockly.wedoLive.valueToCode(a, "DURATION", Blockly.wedoLive.ORDER_ATOMIC);
  Blockly.wedoLive.definitions_.lineTrackOn ||
    ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
    (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  var b = Blockly.wedoLive.definitions_.currentIndent;
  return (
    "#Line track for time\n" +
    b +
    "Ed.StartCountDown(" +
    1e3 * a +
    ", Ed.TIME_MILLISECONDS)\n" +
    b +
    "while Ed.ReadCountDown(Ed.TIME_MILLISECONDS) !=0:\n" +
    b +
    "\tif Ed.ReadLineState()==Ed.LINE_ON_WHITE:\n" +
    b +
    "\t\tEd.Drive(Ed.FORWARD_RIGHT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    b +
    "\telse:\n" +
    b +
    "\t\tEd.Drive(Ed.FORWARD_LEFT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    b +
    "Ed.LineTrackerLed(Ed.OFF)\n"
  );
};

Blockly.wedoLive.drive_stop = function (a) {
  // return (
  //   "#drive stop\n" +
  //   Blockly.wedoLive.definitions_.currentIndent +
  //   "Ed.Drive(Ed.STOP, 0, 0)\n"
  // );
  return (
    Blockly.wedoLive.definitions_.currentIndent +
    "Ed.Drive(Ed.STOP, 0, 0)\n" +
    "#ff5500000000000000\n" 
    
  );
};

Blockly.wedoLive.dropdown_drive_setforwards_event = function (a) {
  a = a.getFieldValue("CHOICE");
  return [driveDropDownToBool(a), Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.drive_forwards_event = function (a) {
  checkForDriveSpeedVar();
  var b = Blockly.wedoLive.definitions_.inLineSpeedtoUse,
    d = "#drive forwards whileEvent\n";
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  var c = Blockly.wedoLive.definitions_.currentIndent;
  Blockly.wedoLive.definitions_.speedChangeInEvent && (b = "DS");
  d = d + c + "Ed.Drive(Ed.FORWARD, " + b + ", Ed.DISTANCE_UNLIMITED)\n";
  "infinite" != a &&
    (d =
      d +
      c +
      "while " +
      a +
      ":\n" +
      c +
      "\tpass\n" +
      c +
      "Ed.Drive(Ed.STOP, 0, 0)\n");
  return d;
};
Blockly.wedoLive.dropdown_drive_setbackwards_event = function (a) {
  a = a.getFieldValue("CHOICE");
  return [driveDropDownToBool(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.drive_backwards_event = function (a) {
  checkForDriveSpeedVar();
  var b = Blockly.wedoLive.definitions_.inLineSpeedtoUse,
    d = "#drive backwards while Event\n";
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  var c = Blockly.wedoLive.definitions_.currentIndent;
  Blockly.wedoLive.definitions_.speedChangeInEvent && (b = "DS");
  d = d + c + "Ed.Drive(Ed.BACKWARD, " + b + ", Ed.DISTANCE_UNLIMITED)\n";
  "infinite" != a &&
    (d =
      d +
      c +
      "while " +
      a +
      ":\n" +
      c +
      "\tpass\n" +
      c +
      "Ed.Drive(Ed.STOP, 0, 0);\n");
  return d;
};
Blockly.wedoLive.dropdown_drive_setleft_event = function (a) {
  a = a.getFieldValue("CHOICE");
  return [driveDropDownToBool(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.drive_left_event = function (a) {
  checkForDriveSpeedVar();
  var b = Blockly.wedoLive.definitions_.inLineSpeedtoUse,
    d = "#drive left while Event\n";
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  var c = Blockly.wedoLive.definitions_.currentIndent;
  Blockly.wedoLive.definitions_.speedChangeInEvent && (b = "DS");
  d = d + c + "Ed.Drive(Ed.FORWARD_LEFT, " + b + ", Ed.DISTANCE_UNLIMITED)\n";
  "infinite" != a &&
    (d =
      d +
      c +
      "while " +
      a +
      ":\n" +
      c +
      "\tpass\n" +
      c +
      "Ed.Drive(Ed.STOP, 0, 0);\n");
  return d;
};
Blockly.wedoLive.dropdown_drive_setright_event = function (a) {
  a = a.getFieldValue("CHOICE");
  return [driveDropDownToBool(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.drive_right_event = function (a) {
  checkForDriveSpeedVar();
  var b = "#drive right while Event\n",
    d = Blockly.wedoLive.definitions_.inLineSpeedtoUse;
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  var c = Blockly.wedoLive.definitions_.currentIndent;
  Blockly.wedoLive.definitions_.speedChangeInEvent && (d = "DS");
  b = b + c + "Ed.Drive(Ed.FORWARD_RIGHT, " + d + ", Ed.DISTANCE_UNLIMITED)\n";
  "infinite" != a &&
    (b =
      b +
      c +
      "while " +
      a +
      ":\n" +
      c +
      "\tpass\n" +
      c +
      "Ed.Drive(Ed.STOP, 0, 0);\n");
  return b;
};
Blockly.wedoLive.drive_line_tracking_obstacle = function (a) {
  Blockly.wedoLive.definitions_.lineTrackOn ||
    ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
    (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  a = "";
  0 == Blockly.wedoLive.definitions_.inObsLoop &&
    (a = "Ed.ObstacleDetectionBeam(Ed.OFF)");
  var b = Blockly.wedoLive.definitions_.currentIndent;
  return (
    "#Line track until obstacle\n" +
    b +
    "Ed.ObstacleDetectionBeam(Ed.ON)\n" +
    b +
    "while Ed.ReadObstacleDetection() == Ed.OBSTACLE_NONE:\n" +
    b +
    "\tif Ed.ReadLineState()==Ed.LINE_ON_WHITE:\n" +
    b +
    "\t\tEd.Drive(Ed.FORWARD_RIGHT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    b +
    "\telse:\n" +
    b +
    "\t\tEd.Drive(Ed.FORWARD_LEFT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    b +
    "Ed.LineTrackerLed(Ed.OFF)\n" +
    b +
    a +
    "\n"
  );
};
Blockly.wedoLive.drive_line_tracking_infinite = function (a) {
  Blockly.wedoLive.definitions_.lineTrackOn ||
    ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
    (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  a = Blockly.wedoLive.definitions_.currentIndent;
  return (
    "#Line track forever\n" +
    a +
    "while True:\n" +
    a +
    "\tif Ed.ReadLineState()==Ed.LINE_ON_WHITE:\n" +
    a +
    "\t\tEd.Drive(Ed.FORWARD_RIGHT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    a +
    "\telse:\n" +
    a +
    "\t\tEd.Drive(Ed.FORWARD_LEFT, Ed.SPEED_1, Ed.DISTANCE_UNLIMITED)\n" +
    a +
    "Ed.LineTrackerLed(Ed.OFF)\n"
  );
};
Blockly.wedoLive.dropdown_drive_setspeed = function (a) {
  return [a.getFieldValue("CHOICE"), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.drive_speed = function (a) {
  checkForDriveSpeedVar();
  Blockly.wedoLive.definitions_.inEvent &&
    (Blockly.wedoLive.definitions_.speedChangeInEvent = !0);
  var b = "#drive set speed\n";
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  var d = Blockly.wedoLive.definitions_.currentIndent;
  Blockly.wedoLive.definitions_.speedChangeInEvent
    ? (b = b + d + "DS = " + a + "\n")
    : (Blockly.wedoLive.definitions_.inLineSpeedtoUse = a);
  return b;
};

function checkForEventUsedVar() {
  0 == Blockly.wedoLive.definitions_.eventUsed &&
    ((Blockly.wedoLive.definitions_.eventUsed = !0),
    (Blockly.wedoLive.definitions_.inEvent = !0));
}

Blockly.wedoLive.new_event_obstacle = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  Blockly.wedoLive.definitions_.Header += "Ed.ObstacleDetectionBeam(Ed.ON)\n";
  return "Ed.RegisterEventHandler(Ed.EVENT_OBSTACLE_ANY, 'if1')\n#obstacle detected event \ndef if1():\nEd.RegisterEventHandler(Ed.EVENT_OBSTACLE_AHEAD, None)\nEd.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadObstacleDetection()\n";
};
Blockly.wedoLive.new_event_clap_one = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  Blockly.wedoLive.definitions_.clapUsed = !0;
  Blockly.wedoLive.definitions_.clapUsedEvent = !0;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n#new clap event \ndef if2():\n\tEd.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadClapSensor()\n\t#clap one event\n";
};
Blockly.wedoLive.new_event_clap_two = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  Blockly.wedoLive.definitions_.clapUsed = !0;
  Blockly.wedoLive.definitions_.clapUsedEvent = !0;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n#new clap event \ndef if2():\n\tEd.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadClapSensor()\n\tEd.TimeWait(350, Ed.TIME_MILLISECONDS)\n\tif Ed.ReadClapSensor() == Ed.CLAP_DETECTED:\n\t\t#clap two event\n\telse:\n";
};
Blockly.wedoLive.new_event_message_1 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 1 event \nif internalIRdata == 1:\n";
};
Blockly.wedoLive.new_event_message_2 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 2 event \nif internalIRdata == 2:\n";
};
Blockly.wedoLive.new_event_message_3 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 3 event \nif internalIRdata == 3:\n";
};
Blockly.wedoLive.new_event_message_4 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 4 event \nif internalIRdata == 4:\n";
};
Blockly.wedoLive.new_event_message_5 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 5 event \nif internalIRdata == 5:\n";
};
Blockly.wedoLive.new_event_message_6 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_IR_DATA, 'if3')\n#new message event \ndef if3():\n\tinternalIRdata = Ed.ReadIRData()\n\tEd.RegisterEventHandler(Ed.EVENT_IR_DATA, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadIRData()\n#IR message 6 event \nif internalIRdata == 6:\n";
};
Blockly.wedoLive.new_event_key_triangle = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_KEYPAD_TRIANGLE, 'if4')\n#triangle button event \ndef if4():\nEd.RegisterEventHandler(Ed.EVENT_KEYPAD_TRIANGLE, None)\nEd.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadKeypad()\n";
};
Blockly.wedoLive.new_event_key_circle = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_KEYPAD_ROUND, 'if5')\n#circle button event \ndef if5():\nEd.RegisterEventHandler(Ed.EVENT_KEYPAD_ROUND, None)\nEd.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadKeypad()\n";
};
Blockly.wedoLive.new_event_line_on_white = function (a) {
  Blockly.wedoLive.definitions_.lineTrackOn ||
    ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
    (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  checkForEventUsedVar();
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  return "Ed.RegisterEventHandler(Ed.EVENT_LINE_TRACKER_ON_WHITE, 'if6')\n#Line on white event  \ndef if6():\nEd.RegisterEventHandler(Ed.EVENT_LINE_TRACKER_ON_WHITE, None)\nEd.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadLineState()\n";
};
Blockly.wedoLive.new_event_line_on_black = function (a) {
  Blockly.wedoLive.definitions_.lineTrackOn ||
    ((Blockly.wedoLive.definitions_.lineTrackOn = !0),
    (Blockly.wedoLive.definitions_.Header += "Ed.LineTrackerLed(Ed.ON)\n"));
  checkForEventUsedVar();
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  return "Ed.RegisterEventHandler(Ed.EVENT_LINE_TRACKER_ON_BLACK, 'if7')\n#Line on black event  \ndef if7():\nEd.RegisterEventHandler(Ed.EVENT_LINE_TRACKER_ON_BLACK, None)\nEd.TimeWait(150, Ed.TIME_MILLISECONDS)\nEd.ReadLineState()\n";
};
Blockly.wedoLive.new_event_remote_code_1 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 1 event  \nif internalRemotedata == 1:\n";
};
Blockly.wedoLive.new_event_remote_code_2 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 2 event  \nif internalRemotedata == 2:\n";
};
Blockly.wedoLive.new_event_remote_code_3 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 3 event  \nif internalRemotedata == 3:\n";
};
Blockly.wedoLive.new_event_remote_code_4 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 4 event  \nif internalRemotedata == 4:\n";
};
Blockly.wedoLive.new_event_remote_code_5 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 5 event  \nif internalRemotedata == 5:\n";
};
Blockly.wedoLive.new_event_remote_code_6 = function (a) {
  Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  checkForEventUsedVar();
  return "Ed.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, 'if8')\n#new remote event \ndef if8():\n\tinternalRemotedata = Ed.ReadRemote()\n\tEd.RegisterEventHandler(Ed.EVENT_REMOTE_CODE, None)\n\tEd.TimeWait(150, Ed.TIME_MILLISECONDS)\n\tEd.ReadRemote()\n#Remote message 6 event  \nif internalRemotedata == 6:\n";
};
Blockly.wedoLive.LightsSound = {};
function soundDropDownToNote(a) {
  var b = "";
  if (1 == Blockly.wedoLive.definitions_.nextNoteSharp) {
    switch (a) {
      case "Chigh":
        b = "o";
        break;
      case "Bhigh":
        b = "o";
        break;
      case "A":
        b = "A";
        break;
      case "G":
        b = "G";
        break;
      case "F":
        b = "F";
        break;
      case "E":
        b = "f";
        break;
      case "D":
        b = "D";
        break;
      case "C":
        b = "C";
        break;
      case "B":
        b = "c";
    }
    Blockly.wedoLive.definitions_.nextNoteSharp = !1;
  } else
    switch (a) {
      case "Chigh":
        b = "o";
        break;
      case "Bhigh":
        b = "b";
        break;
      case "A":
        b = "a";
        break;
      case "G":
        b = "g";
        break;
      case "F":
        b = "f";
        break;
      case "E":
        b = "e";
        break;
      case "D":
        b = "d";
        break;
      case "C":
        b = "c";
        break;
      case "B":
        b = "n";
    }
  return b;
}
Blockly.wedoLive.dropdown_light_sound_LED = function (a) {
  return [a.getFieldValue("CHOICE"), Blockly.wedoLive.ORDER_ATOMIC];
};

Blockly.wedoLive.light_sound_beep = function (a) {
  var b = "Ed.TimeWait(125,Ed.TIME_MILLISECONDS) \n",
    d = Blockly.wedoLive.definitions_.currentIndent;
  if (null != a.getNextBlock()) {
    var c = a.getNextBlock().type;
    console.log(c);
    if (
      (c.includes("drive") && "drive_stop" != c && "drive_speed" != c) ||
      c.includes("_wait_")
    )
      b = "";
  }
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (b =
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        d +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        d +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  return "#BEEEEEEP!\n" + d + "Ed.PlayBeep()\n" + d + b;
};
Blockly.wedoLive.dropdown_light_sound_play_whole = function (a) {
  a = a.getFieldValue("CHOICE");
  return [soundDropDownToNote(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_play_whole = function (a) {
  var b = "#Play whole note\n";
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  var d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC),
    c = Blockly.wedoLive.definitions_.currentIndent,
    e = Blockly.wedoLive.definitions_.musicStackFlag,
    f = a.nextConnection.targetBlock(),
    g = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (g =
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        c +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  null != f
    ? f.type.includes("light_sound_play_") ||
      "light_sound_rest" == f.type ||
      "light_sound_note_sharp" == f.type
      ? ((Blockly.wedoLive.definitions_.musicStackFlag = !0),
        (Blockly.wedoLive.definitions_.musicStackString =
          Blockly.wedoLive.definitions_.musicStackString + d + "1"),
        (b = "#Play note stacked\n"))
      : (e
          ? ((Blockly.wedoLive.definitions_.musicStackString =
              Blockly.wedoLive.definitions_.musicStackString + d + "1"),
            (b =
              b +
              c +
              "Ed.PlayTune('" +
              Blockly.wedoLive.definitions_.musicStackString +
              "z')\n"),
            (b =
              b +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g))
          : (b =
              b +
              c +
              "Ed.PlayTune('" +
              d +
              "1z')\n" +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = ""))
    : (e
        ? ((Blockly.wedoLive.definitions_.musicStackString =
            Blockly.wedoLive.definitions_.musicStackString + d + "1"),
          (b =
            b +
            c +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"))
        : (b =
            b +
            c +
            "Ed.PlayTune('" +
            d +
            "1z')\n" +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"),
      (b += g),
      (Blockly.wedoLive.definitions_.musicStackFlag = !1),
      (Blockly.wedoLive.definitions_.musicStackString = ""));
  return b;
};
Blockly.wedoLive.dropdown_light_sound_play_half = function (a) {
  a = a.getFieldValue("CHOICE");
  return [soundDropDownToNote(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_play_half = function (a) {
  var b = "#Play half note\n";
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  var d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC),
    c = Blockly.wedoLive.definitions_.currentIndent,
    e = Blockly.wedoLive.definitions_.musicStackFlag,
    f = a.nextConnection.targetBlock(),
    g = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (g =
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        c +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  null != f
    ? f.type.includes("light_sound_play_") ||
      "light_sound_rest" == f.type ||
      "light_sound_note_sharp" == f.type
      ? ((Blockly.wedoLive.definitions_.musicStackFlag = !0),
        (Blockly.wedoLive.definitions_.musicStackString =
          Blockly.wedoLive.definitions_.musicStackString + d + "2"),
        (b = "#Play note stacked\n"))
      : (e
          ? ((Blockly.wedoLive.definitions_.musicStackString =
              Blockly.wedoLive.definitions_.musicStackString + d + "2"),
            (b =
              b +
              c +
              "Ed.PlayTune('" +
              Blockly.wedoLive.definitions_.musicStackString +
              "z')\n"),
            (b =
              b +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g))
          : (b =
              b +
              c +
              "Ed.PlayTune('" +
              d +
              "2z')\n" +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = ""))
    : (e
        ? ((Blockly.wedoLive.definitions_.musicStackString =
            Blockly.wedoLive.definitions_.musicStackString + d + "2"),
          (b =
            b +
            c +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"))
        : (b =
            b +
            c +
            "Ed.PlayTune('" +
            d +
            "2z')\n" +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"),
      (b += g),
      (Blockly.wedoLive.definitions_.musicStackFlag = !1),
      (Blockly.wedoLive.definitions_.musicStackString = ""));
  return b;
};
Blockly.wedoLive.dropdown_light_sound_play_quarter = function (a) {
  a = a.getFieldValue("CHOICE");
  return [soundDropDownToNote(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_play_quarter = function (a) {
  var b = "#Play quarter note\n";
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  var d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC),
    c = Blockly.wedoLive.definitions_.currentIndent,
    e = Blockly.wedoLive.definitions_.musicStackFlag,
    f = a.nextConnection.targetBlock(),
    g = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (g =
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        c +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  null != f
    ? f.type.includes("light_sound_play_") ||
      "light_sound_rest" == f.type ||
      "light_sound_note_sharp" == f.type
      ? ((Blockly.wedoLive.definitions_.musicStackFlag = !0),
        (Blockly.wedoLive.definitions_.musicStackString =
          Blockly.wedoLive.definitions_.musicStackString + d + "4"),
        (b = "#Play note stacked\n"))
      : (e
          ? ((Blockly.wedoLive.definitions_.musicStackString =
              Blockly.wedoLive.definitions_.musicStackString + d + "4"),
            (b =
              b +
              c +
              "Ed.PlayTune('" +
              Blockly.wedoLive.definitions_.musicStackString +
              "z')\n"),
            (b =
              b +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g))
          : (b =
              b +
              c +
              "Ed.PlayTune('" +
              d +
              "4z')\n" +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = ""))
    : (e
        ? ((Blockly.wedoLive.definitions_.musicStackString =
            Blockly.wedoLive.definitions_.musicStackString + d + "4"),
          (b =
            b +
            c +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"))
        : (b =
            b +
            c +
            "Ed.PlayTune('" +
            d +
            "4z')\n" +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"),
      (b += g),
      (Blockly.wedoLive.definitions_.musicStackFlag = !1),
      (Blockly.wedoLive.definitions_.musicStackString = ""));
  return b;
};
Blockly.wedoLive.dropdown_light_sound_play_eighth = function (a) {
  a = a.getFieldValue("CHOICE");
  return [soundDropDownToNote(a), Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_play_eighth = function (a) {
  var b = "#Play eighth note\n";
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  var d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC),
    c = Blockly.wedoLive.definitions_.currentIndent,
    e = Blockly.wedoLive.definitions_.musicStackFlag,
    f = a.nextConnection.targetBlock(),
    g = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (g =
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        c +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  null != f
    ? f.type.includes("light_sound_play_") ||
      "light_sound_rest" == f.type ||
      "light_sound_note_sharp" == f.type
      ? ((Blockly.wedoLive.definitions_.musicStackFlag = !0),
        (Blockly.wedoLive.definitions_.musicStackString =
          Blockly.wedoLive.definitions_.musicStackString + d + "8"),
        (b = "#Play note stacked\n"))
      : (e
          ? ((Blockly.wedoLive.definitions_.musicStackString =
              Blockly.wedoLive.definitions_.musicStackString + d + "8"),
            (b =
              b +
              c +
              "Ed.PlayTune('" +
              Blockly.wedoLive.definitions_.musicStackString +
              "z')\n"),
            (b =
              b +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g))
          : (b =
              b +
              c +
              "Ed.PlayTune('" +
              d +
              "8z')\n" +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = ""))
    : (e
        ? ((Blockly.wedoLive.definitions_.musicStackString =
            Blockly.wedoLive.definitions_.musicStackString + d + "8"),
          (b =
            b +
            c +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"))
        : (b =
            b +
            c +
            "Ed.PlayTune('" +
            d +
            "8z')\n" +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"),
      (b += g),
      (Blockly.wedoLive.definitions_.musicStackFlag = !1),
      (Blockly.wedoLive.definitions_.musicStackString = ""));
  return b;
};
Blockly.wedoLive.light_sound_note_sharp = function (a) {
  var b = "";
  Blockly.wedoLive.definitions_.nextNoteSharp = !0;
  var d = Blockly.wedoLive.definitions_.musicStackFlag,
    c = a.nextConnection.targetBlock(),
    e = Blockly.wedoLive.definitions_.currentIndent,
    f = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (f =
        e +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        e +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        e +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  d &&
    (null != c
      ? c.type.includes("light_sound_play_") ||
        "light_sound_rest" == c.type ||
        "light_sound_note_sharp" == c.type
        ? (b = "#Next note sharp\n")
        : ((b =
            b +
            e +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            e +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            e +
            "\tpass\n" +
            f),
          (Blockly.wedoLive.definitions_.musicStackFlag = !1),
          (Blockly.wedoLive.definitions_.musicStackString = ""))
      : ((b =
          b +
          e +
          "Ed.PlayTune('" +
          Blockly.wedoLive.definitions_.musicStackString +
          "z')\n"),
        (b =
          b +
          e +
          "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
          e +
          "\tpass\n" +
          f),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = "")));
  return b;
};
Blockly.wedoLive.dropdown_light_sound_note_tempo = function (a) {
  switch (a.getFieldValue("CHOICE")) {
    case "4":
      var b = "Ed.TEMPO_SLOW";
      break;
    case "2":
      b = "Ed.TEMPO_MEDIUM";
      break;
    case "1":
      b = "Ed.TEMPO_FAST";
  }
  return [b, Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_note_tempo = function (a) {
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  a = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC);
  return (
    "#set tempo\n" +
    Blockly.wedoLive.definitions_.currentIndent +
    "Ed.Tempo = " +
    a +
    "\n"
  );
};
Blockly.wedoLive.dropdown_light_sound_rest = function (a) {
  switch (a.getFieldValue("CHOICE")) {
    case "100":
      var b = "1";
      break;
    case "50":
      b = "2";
      break;
    case "25":
      b = "4";
      break;
    case "12":
      b = "8";
  }
  return [b, Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.light_sound_rest = function (a) {
  var b = "#Play rest note\n";
  Blockly.wedoLive.definitions_.MusicUsed = !0;
  var d = Blockly.wedoLive.valueToCode(a, "CHOICE", Blockly.wedoLive.ORDER_ATOMIC),
    c = Blockly.wedoLive.definitions_.currentIndent,
    e = Blockly.wedoLive.definitions_.musicStackFlag,
    f = a.nextConnection.targetBlock(),
    g = "";
  Blockly.wedoLive.definitions_.clapUsedEvent &&
    (a.getRootBlock().type.includes("new_event_clap_") ||
      (g =
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, None)\n" +
        c +
        "Ed.TimeWait(150, Ed.TIME_MILLISECONDS)\n" +
        c +
        "Ed.RegisterEventHandler(Ed.EVENT_CLAP_DETECTED, 'if2')\n"));
  null != f
    ? f.type.includes("light_sound_play_") ||
      "light_sound_rest" == f.type ||
      "light_sound_note_sharp" == f.type
      ? ((Blockly.wedoLive.definitions_.musicStackFlag = !0),
        (Blockly.wedoLive.definitions_.musicStackString =
          Blockly.wedoLive.definitions_.musicStackString + "r" + d),
        (b = "#Play note stacked\n"))
      : (e
          ? ((Blockly.wedoLive.definitions_.musicStackString =
              Blockly.wedoLive.definitions_.musicStackString + "r" + d),
            (b =
              b +
              c +
              "Ed.PlayTune('" +
              Blockly.wedoLive.definitions_.musicStackString +
              "z')\n"),
            (b =
              b +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g))
          : (b =
              b +
              c +
              "Ed.PlayTune('r" +
              d +
              "z')\n" +
              c +
              "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
              c +
              "\tpass\n" +
              g),
        (Blockly.wedoLive.definitions_.musicStackFlag = !1),
        (Blockly.wedoLive.definitions_.musicStackString = ""))
    : (e
        ? ((Blockly.wedoLive.definitions_.musicStackString =
            Blockly.wedoLive.definitions_.musicStackString + "r" + d),
          (b =
            b +
            c +
            "Ed.PlayTune('" +
            Blockly.wedoLive.definitions_.musicStackString +
            "z')\n"),
          (b =
            b +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"))
        : (b =
            b +
            c +
            "Ed.PlayTune('r" +
            d +
            "z')\n" +
            c +
            "while Ed.ReadMusicEnd()==Ed.MUSIC_NOT_FINISHED:\n" +
            c +
            "\tpass\n"),
      (b += g),
      (Blockly.wedoLive.definitions_.musicStackFlag = !1),
      (Blockly.wedoLive.definitions_.musicStackString = ""));
  return b;
};
Blockly.wedoLive.Math = {};
Blockly.wedoLive.math_angle = function (a) {
  a = parseInt(a.getFieldValue("NUM"));
  isNaN(a) && (a = 0);
  0 > a && (a = 0);
  return [a, Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.math_angle_CC = function (a) {
  a = parseInt(a.getFieldValue("NUM"));
  isNaN(a) && (a = 0);
  0 > a && (a = 0);
  return [a, Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.math_whole_number = function (a) {
  a = parseInt(a.getFieldValue("NUM"));
  isNaN(a) && (a = 0);
  0 > a && (a = 0);
  return [a, Blockly.wedoLive.ORDER_ATOMIC];
};
Blockly.wedoLive.math_positive_number = function (a) {
  a = parseFloat(a.getFieldValue("NUM"));
  isNaN(a) && (a = 0);
  0 > a && (a = 0);
  return [a, Blockly.wedoLive.ORDER_ATOMIC];
};

function toTwoByteHex(value) {
  if (value < 0 || value > 65535) {
      console.error("Value out of range (0-65535)");
      return null;
  }

  let highByte = (value >> 8) & 0xFF;
  let lowByte = value & 0xFF;
  // console.log(`High Byte: 0x${highByte.toString(16).padStart(2, '0').toUpperCase()}, Low Byte: 0x${lowByte.toString(16).padStart(2, '0').toUpperCase()}`);
  return {
      high: highByte.toString(16).padStart(2, '0').toUpperCase(),
      low: lowByte.toString(16).padStart(2, '0').toUpperCase()
  };
}

function HexColorToRGB(colourValue)
{
    var hexRed, hexGreen, hexBlue;
    var red, green, blue;
    hexRed = colourValue.substring(0, 2);
    hexGreen = colourValue.substring(2, 4);
    hexBlue = colourValue.substring(4, 6);
    red = parseInt(hexRed, 16).toString(16).padStart(2, '0').toUpperCase();
    green = parseInt(hexGreen, 16).toString(16).padStart(2, '0').toUpperCase();
    blue = parseInt(hexBlue, 16).toString(16).padStart(2, '0').toUpperCase();
    var code =  red + " " + green + " " + blue;
    return code;
}

function matrix_Binary_to_four_segments(binaryString ){
  const hexArray = [];
  for (let i = 0; i < 128; i += 8) {
    const byte = binaryString.slice(i, i + 8);
    hexArray.push(parseInt(byte, 2));
  }
  
  // Split into 4 packets of 4 bytes each
  const segments = [];
  for (let i = 0; i < 16; i += 4) {
    const chunk = hexArray.slice(i, i + 4);
    const packet = [0xFF, 0x55, 0x04, ...chunk];
    const hexPacket = packet.map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(' ');
    segments.push(hexPacket);
  }
  
  // Join all packets with "-"
  const finalString = segments.join('-');
  // console.log(finalString);
  return finalString;
}

function stringToFormattedHexChunks(str) {
  const result = [];
  for (let i = 0; i < str.length; i += 4) {
    let chunk = str.slice(i, i + 4);
    const hexChars = [];

    for (let j = 0; j < 4; j++) {
      if (j < chunk.length) {
        hexChars.push(chunk.charCodeAt(j).toString(16).padStart(2, '0').toUpperCase());
      } else {
        // Pad with 00 instead of space if end of string
        hexChars.push("00");
      }
    }

    result.push(`FF 55 03 ${hexChars.join(' ')}`);
  }
  return result.join('-');
}